// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const accountHasEntries = `-- name: AccountHasEntries :one
SELECT EXISTS (
    SELECT 1
    FROM entries
    WHERE account_id = $1
)
`

func (q *Queries) AccountHasEntries(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountHasEntries, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (owner_id, name, currency, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, balance, currency, is_system, created_at
`

type CreateAccountParams struct {
	OwnerID  uuid.NullUUID `json:"owner_id"`
	Name     string        `json:"name"`
	Currency string        `json:"currency"`
	IsSystem bool          `json:"is_system"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.OwnerID,
		arg.Name,
		arg.Currency,
		arg.IsSystem,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM accounts
WHERE accounts.id = $1
  AND accounts.owner_id = $2
  AND accounts.is_system = FALSE
  AND accounts.balance = 0
  AND NOT EXISTS (
      SELECT 1
      FROM entries
      WHERE entries.account_id = accounts.id
  )
RETURNING accounts.id, accounts.owner_id, accounts.name, accounts.balance, accounts.currency, accounts.is_system, accounts.created_at
`

type DeleteAccountParams struct {
	AccountID uuid.UUID     `json:"account_id"`
	OwnerID   uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, deleteAccount, arg.AccountID, arg.OwnerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one

SELECT CAST((COALESCE(SUM(credit), 0::NUMERIC) - COALESCE(SUM(debit), 0::NUMERIC)) AS NUMERIC(19,4)) AS calculated_balance
FROM entries
WHERE account_id = $1
`

// lock prevents concurrent transactions from reading a stale balance.
func (q *Queries) GetAccountBalance(ctx context.Context, accountID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, accountID)
	var calculated_balance string
	err := row.Scan(&calculated_balance)
	return calculated_balance, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementAccount = `-- name: GetSettlementAccount :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE is_system = TRUE AND name = 'Settlement Account'
LIMIT 1
`

func (q *Queries) GetSettlementAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRowContext(ctx, getSettlementAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementAccountForUpdate = `-- name: GetSettlementAccountForUpdate :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE is_system = TRUE AND name = 'Settlement Account'
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetSettlementAccountForUpdate(ctx context.Context) (Account, error) {
	row := q.db.QueryRowContext(ctx, getSettlementAccountForUpdate)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many

SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE owner_id = $1
ORDER BY created_at DESC
`

// locks row for update, prevents TOCTOU races
func (q *Queries) ListAccountsByOwner(ctx context.Context, ownerID uuid.NullUUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Balance,
			&i.Currency,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1
WHERE accounts.id = $2
  AND accounts.owner_id = $3
  AND accounts.is_system = FALSE
RETURNING accounts.id, accounts.owner_id, accounts.name, accounts.balance, accounts.currency, accounts.is_system, accounts.created_at
`

type UpdateAccountParams struct {
	Name      string        `json:"name"`
	AccountID uuid.UUID     `json:"account_id"`
	OwnerID   uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.Name, arg.AccountID, arg.OwnerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + $1
WHERE id = $2
`

type UpdateAccountBalanceParams struct {
	Balance string    `json:"balance"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountBalance, arg.Balance, arg.ID)
	return err
}
