// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelPaymentOrder = `-- name: CancelPaymentOrder :one
UPDATE payment_orders
SET status = 'CANCELLED', updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND owner_id = $2
  AND status IN ('DRAFT', 'AWAITING_CONFIRMATION', 'SCHEDULED')
RETURNING id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at
`

type CancelPaymentOrderParams struct {
	PaymentOrderID uuid.UUID `json:"payment_order_id"`
	OwnerID        uuid.UUID `json:"owner_id"`
}

func (q *Queries) CancelPaymentOrder(ctx context.Context, arg CancelPaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, cancelPaymentOrder, arg.PaymentOrderID, arg.OwnerID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const claimDuePaymentOrders = `-- name: ClaimDuePaymentOrders :many
WITH due AS (
    SELECT id
    FROM payment_orders
    WHERE status = 'SCHEDULED' AND requested_execution_at <= CURRENT_TIMESTAMP
    ORDER BY requested_execution_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE payment_orders AS payment
SET status = 'PROCESSING', processing_started_at = CURRENT_TIMESTAMP,
    attempt_count = payment.attempt_count + 1, updated_at = CURRENT_TIMESTAMP
FROM due
WHERE payment.id = due.id
RETURNING payment.id, payment.owner_id, payment.source_account_id, payment.beneficiary_account_id, payment.standing_order_id, payment.beneficiary_name, payment.beneficiary_iban, payment.beneficiary_bic, payment.amount, payment.currency, payment.payment_kind, payment.schedule_type, payment.purpose, payment.creditor_reference, payment.end_to_end_id, payment.idempotency_key, payment.requested_execution_at, payment.vop_result, payment.vop_suggested_name, payment.vop_overridden, payment.vop_decision_at, payment.status, payment.reject_code, payment.failure_reason, payment.ledger_transaction_id, payment.attempt_count, payment.processing_started_at, payment.created_at, payment.updated_at, payment.processed_at
`

func (q *Queries) ClaimDuePaymentOrders(ctx context.Context, batchSize int32) ([]PaymentOrder, error) {
	rows, err := q.db.QueryContext(ctx, claimDuePaymentOrders, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentOrder
	for rows.Next() {
		var i PaymentOrder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.SourceAccountID,
			&i.BeneficiaryAccountID,
			&i.StandingOrderID,
			&i.BeneficiaryName,
			&i.BeneficiaryIban,
			&i.BeneficiaryBic,
			&i.Amount,
			&i.Currency,
			&i.PaymentKind,
			&i.ScheduleType,
			&i.Purpose,
			&i.CreditorReference,
			&i.EndToEndID,
			&i.IdempotencyKey,
			&i.RequestedExecutionAt,
			&i.VopResult,
			&i.VopSuggestedName,
			&i.VopOverridden,
			&i.VopDecisionAt,
			&i.Status,
			&i.RejectCode,
			&i.FailureReason,
			&i.LedgerTransactionID,
			&i.AttemptCount,
			&i.ProcessingStartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const confirmPaymentOrder = `-- name: ConfirmPaymentOrder :one
UPDATE payment_orders
SET status = $1,
    vop_overridden = $2,
    vop_decision_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
  AND owner_id = $4
  AND status = 'AWAITING_CONFIRMATION'
RETURNING id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at
`

type ConfirmPaymentOrderParams struct {
	Status         string    `json:"status"`
	VopOverridden  bool      `json:"vop_overridden"`
	PaymentOrderID uuid.UUID `json:"payment_order_id"`
	OwnerID        uuid.UUID `json:"owner_id"`
}

func (q *Queries) ConfirmPaymentOrder(ctx context.Context, arg ConfirmPaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, confirmPaymentOrder,
		arg.Status,
		arg.VopOverridden,
		arg.PaymentOrderID,
		arg.OwnerID,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (owner_id, payment_order_id, event_type, event_data)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, payment_order_id, event_type, event_data, created_at
`

type CreateAuditEventParams struct {
	OwnerID        uuid.NullUUID   `json:"owner_id"`
	PaymentOrderID uuid.NullUUID   `json:"payment_order_id"`
	EventType      string          `json:"event_type"`
	EventData      json.RawMessage `json:"event_data"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuditEvent,
		arg.OwnerID,
		arg.PaymentOrderID,
		arg.EventType,
		arg.EventData,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PaymentOrderID,
		&i.EventType,
		&i.EventData,
		&i.CreatedAt,
	)
	return i, err
}

const createBeneficiary = `-- name: CreateBeneficiary :one
INSERT INTO beneficiaries (owner_id, name, iban, bic, category)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, iban) DO UPDATE
SET name = EXCLUDED.name, bic = EXCLUDED.bic, category = EXCLUDED.category,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, owner_id, name, iban, bic, category, is_demo, created_at, updated_at
`

type CreateBeneficiaryParams struct {
	OwnerID  uuid.UUID      `json:"owner_id"`
	Name     string         `json:"name"`
	Iban     string         `json:"iban"`
	Bic      sql.NullString `json:"bic"`
	Category sql.NullString `json:"category"`
}

func (q *Queries) CreateBeneficiary(ctx context.Context, arg CreateBeneficiaryParams) (Beneficiary, error) {
	row := q.db.QueryRowContext(ctx, createBeneficiary,
		arg.OwnerID,
		arg.Name,
		arg.Iban,
		arg.Bic,
		arg.Category,
	)
	var i Beneficiary
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Iban,
		&i.Bic,
		&i.Category,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentOrder = `-- name: CreatePaymentOrder :one
INSERT INTO payment_orders (
    owner_id, source_account_id, beneficiary_account_id, standing_order_id,
    beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency,
    payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id,
    idempotency_key, requested_execution_at, vop_result, vop_suggested_name,
    status
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, 'EUR',
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18
)
RETURNING id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at
`

type CreatePaymentOrderParams struct {
	OwnerID              uuid.UUID      `json:"owner_id"`
	SourceAccountID      uuid.UUID      `json:"source_account_id"`
	BeneficiaryAccountID uuid.NullUUID  `json:"beneficiary_account_id"`
	StandingOrderID      uuid.NullUUID  `json:"standing_order_id"`
	BeneficiaryName      string         `json:"beneficiary_name"`
	BeneficiaryIban      string         `json:"beneficiary_iban"`
	BeneficiaryBic       sql.NullString `json:"beneficiary_bic"`
	Amount               string         `json:"amount"`
	PaymentKind          string         `json:"payment_kind"`
	ScheduleType         string         `json:"schedule_type"`
	Purpose              sql.NullString `json:"purpose"`
	CreditorReference    sql.NullString `json:"creditor_reference"`
	EndToEndID           string         `json:"end_to_end_id"`
	IdempotencyKey       string         `json:"idempotency_key"`
	RequestedExecutionAt time.Time      `json:"requested_execution_at"`
	VopResult            string         `json:"vop_result"`
	VopSuggestedName     sql.NullString `json:"vop_suggested_name"`
	Status               string         `json:"status"`
}

func (q *Queries) CreatePaymentOrder(ctx context.Context, arg CreatePaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, createPaymentOrder,
		arg.OwnerID,
		arg.SourceAccountID,
		arg.BeneficiaryAccountID,
		arg.StandingOrderID,
		arg.BeneficiaryName,
		arg.BeneficiaryIban,
		arg.BeneficiaryBic,
		arg.Amount,
		arg.PaymentKind,
		arg.ScheduleType,
		arg.Purpose,
		arg.CreditorReference,
		arg.EndToEndID,
		arg.IdempotencyKey,
		arg.RequestedExecutionAt,
		arg.VopResult,
		arg.VopSuggestedName,
		arg.Status,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteBeneficiary = `-- name: DeleteBeneficiary :execrows
DELETE FROM beneficiaries WHERE id = $1 AND owner_id = $2
`

type DeleteBeneficiaryParams struct {
	BeneficiaryID uuid.UUID `json:"beneficiary_id"`
	OwnerID       uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteBeneficiary(ctx context.Context, arg DeleteBeneficiaryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBeneficiary, arg.BeneficiaryID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBeneficiaryByIBAN = `-- name: GetBeneficiaryByIBAN :one
SELECT id, owner_id, name, iban, bic, category, is_demo, created_at, updated_at FROM beneficiaries
WHERE owner_id = $1 AND iban = $2
LIMIT 1
`

type GetBeneficiaryByIBANParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Iban    string    `json:"iban"`
}

func (q *Queries) GetBeneficiaryByIBAN(ctx context.Context, arg GetBeneficiaryByIBANParams) (Beneficiary, error) {
	row := q.db.QueryRowContext(ctx, getBeneficiaryByIBAN, arg.OwnerID, arg.Iban)
	var i Beneficiary
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Iban,
		&i.Bic,
		&i.Category,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentOrder = `-- name: GetPaymentOrder :one
SELECT id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at FROM payment_orders WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentOrder(ctx context.Context, id uuid.UUID) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, getPaymentOrder, id)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPaymentOrderByIdempotency = `-- name: GetPaymentOrderByIdempotency :one
SELECT id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at FROM payment_orders
WHERE owner_id = $1 AND idempotency_key = $2
LIMIT 1
`

type GetPaymentOrderByIdempotencyParams struct {
	OwnerID        uuid.UUID `json:"owner_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetPaymentOrderByIdempotency(ctx context.Context, arg GetPaymentOrderByIdempotencyParams) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, getPaymentOrderByIdempotency, arg.OwnerID, arg.IdempotencyKey)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPaymentOrderForUpdate = `-- name: GetPaymentOrderForUpdate :one
SELECT id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at FROM payment_orders WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetPaymentOrderForUpdate(ctx context.Context, id uuid.UUID) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, getPaymentOrderForUpdate, id)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listAuditEventsAfter = `-- name: ListAuditEventsAfter :many
SELECT id, owner_id, payment_order_id, event_type, event_data, created_at FROM audit_events
WHERE owner_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListAuditEventsAfterParams struct {
	OwnerID     uuid.NullUUID `json:"owner_id"`
	AfterID     int64         `json:"after_id"`
	ResultLimit int32         `json:"result_limit"`
}

func (q *Queries) ListAuditEventsAfter(ctx context.Context, arg ListAuditEventsAfterParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsAfter, arg.OwnerID, arg.AfterID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.PaymentOrderID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeneficiaries = `-- name: ListBeneficiaries :many
SELECT id, owner_id, name, iban, bic, category, is_demo, created_at, updated_at FROM beneficiaries WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListBeneficiaries(ctx context.Context, ownerID uuid.UUID) ([]Beneficiary, error) {
	rows, err := q.db.QueryContext(ctx, listBeneficiaries, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Beneficiary
	for rows.Next() {
		var i Beneficiary
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Iban,
			&i.Bic,
			&i.Category,
			&i.IsDemo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentOrdersByOwner = `-- name: ListPaymentOrdersByOwner :many
SELECT id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at FROM payment_orders
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListPaymentOrdersByOwnerParams struct {
	OwnerID      uuid.UUID `json:"owner_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

func (q *Queries) ListPaymentOrdersByOwner(ctx context.Context, arg ListPaymentOrdersByOwnerParams) ([]PaymentOrder, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentOrdersByOwner, arg.OwnerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentOrder
	for rows.Next() {
		var i PaymentOrder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.SourceAccountID,
			&i.BeneficiaryAccountID,
			&i.StandingOrderID,
			&i.BeneficiaryName,
			&i.BeneficiaryIban,
			&i.BeneficiaryBic,
			&i.Amount,
			&i.Currency,
			&i.PaymentKind,
			&i.ScheduleType,
			&i.Purpose,
			&i.CreditorReference,
			&i.EndToEndID,
			&i.IdempotencyKey,
			&i.RequestedExecutionAt,
			&i.VopResult,
			&i.VopSuggestedName,
			&i.VopOverridden,
			&i.VopDecisionAt,
			&i.Status,
			&i.RejectCode,
			&i.FailureReason,
			&i.LedgerTransactionID,
			&i.AttemptCount,
			&i.ProcessingStartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPayeeByIBAN = `-- name: LookupPayeeByIBAN :one
SELECT accounts.id AS account_id, accounts.owner_id, users.full_name, accounts.status
FROM accounts
JOIN users ON users.id = accounts.owner_id
WHERE accounts.iban = $1 AND accounts.is_system = FALSE
LIMIT 1
`

type LookupPayeeByIBANRow struct {
	AccountID uuid.UUID     `json:"account_id"`
	OwnerID   uuid.NullUUID `json:"owner_id"`
	FullName  string        `json:"full_name"`
	Status    string        `json:"status"`
}

func (q *Queries) LookupPayeeByIBAN(ctx context.Context, iban string) (LookupPayeeByIBANRow, error) {
	row := q.db.QueryRowContext(ctx, lookupPayeeByIBAN, iban)
	var i LookupPayeeByIBANRow
	err := row.Scan(
		&i.AccountID,
		&i.OwnerID,
		&i.FullName,
		&i.Status,
	)
	return i, err
}

const markPaymentBooked = `-- name: MarkPaymentBooked :one
UPDATE payment_orders
SET status = 'BOOKED', ledger_transaction_id = $1,
    processed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP,
    failure_reason = NULL, reject_code = NULL
WHERE id = $2
  AND status = 'PROCESSING'
  AND ledger_transaction_id IS NULL
RETURNING id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at
`

type MarkPaymentBookedParams struct {
	LedgerTransactionID uuid.NullUUID `json:"ledger_transaction_id"`
	PaymentOrderID      uuid.UUID     `json:"payment_order_id"`
}

func (q *Queries) MarkPaymentBooked(ctx context.Context, arg MarkPaymentBookedParams) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, markPaymentBooked, arg.LedgerTransactionID, arg.PaymentOrderID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payment_orders
SET status = 'FAILED', failure_reason = $1,
    reject_code = $2, processed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND status = 'PROCESSING'
RETURNING id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at
`

type MarkPaymentFailedParams struct {
	FailureReason  sql.NullString `json:"failure_reason"`
	RejectCode     sql.NullString `json:"reject_code"`
	PaymentOrderID uuid.UUID      `json:"payment_order_id"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, markPaymentFailed, arg.FailureReason, arg.RejectCode, arg.PaymentOrderID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markPaymentProcessing = `-- name: MarkPaymentProcessing :one
UPDATE payment_orders
SET status = 'PROCESSING', processing_started_at = CURRENT_TIMESTAMP,
    attempt_count = attempt_count + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND status IN ('AWAITING_CONFIRMATION', 'SCHEDULED')
RETURNING id, owner_id, source_account_id, beneficiary_account_id, standing_order_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, payment_kind, schedule_type, purpose, creditor_reference, end_to_end_id, idempotency_key, requested_execution_at, vop_result, vop_suggested_name, vop_overridden, vop_decision_at, status, reject_code, failure_reason, ledger_transaction_id, attempt_count, processing_started_at, created_at, updated_at, processed_at
`

func (q *Queries) MarkPaymentProcessing(ctx context.Context, paymentOrderID uuid.UUID) (PaymentOrder, error) {
	row := q.db.QueryRowContext(ctx, markPaymentProcessing, paymentOrderID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.StandingOrderID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.PaymentKind,
		&i.ScheduleType,
		&i.Purpose,
		&i.CreditorReference,
		&i.EndToEndID,
		&i.IdempotencyKey,
		&i.RequestedExecutionAt,
		&i.VopResult,
		&i.VopSuggestedName,
		&i.VopOverridden,
		&i.VopDecisionAt,
		&i.Status,
		&i.RejectCode,
		&i.FailureReason,
		&i.LedgerTransactionID,
		&i.AttemptCount,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const recoverStalePayments = `-- name: RecoverStalePayments :execrows
UPDATE payment_orders
SET status = 'SCHEDULED', processing_started_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE status = 'PROCESSING'
  AND ledger_transaction_id IS NULL
  AND processing_started_at < CURRENT_TIMESTAMP - make_interval(secs => $1::INT)
`

func (q *Queries) RecoverStalePayments(ctx context.Context, staleSeconds int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverStalePayments, staleSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
