// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AccountHasEntries(ctx context.Context, accountID uuid.UUID) (bool, error)
	AdvanceStandingOrder(ctx context.Context, arg AdvanceStandingOrderParams) (StandingOrder, error)
	CancelPaymentOrder(ctx context.Context, arg CancelPaymentOrderParams) (PaymentOrder, error)
	ClaimDuePaymentOrders(ctx context.Context, batchSize int32) ([]PaymentOrder, error)
	ClaimDueStandingOrders(ctx context.Context, batchSize int32) ([]StandingOrder, error)
	ConfirmPaymentOrder(ctx context.Context, arg ConfirmPaymentOrderParams) (PaymentOrder, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateBeneficiary(ctx context.Context, arg CreateBeneficiaryParams) (Beneficiary, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreatePaymentEntry(ctx context.Context, arg CreatePaymentEntryParams) (Entry, error)
	CreatePaymentOrder(ctx context.Context, arg CreatePaymentOrderParams) (PaymentOrder, error)
	CreateStandingOrder(ctx context.Context, arg CreateStandingOrderParams) (StandingOrder, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (Account, error)
	DeleteBeneficiary(ctx context.Context, arg DeleteBeneficiaryParams) (int64, error)
	DeleteStandingOrder(ctx context.Context, arg DeleteStandingOrderParams) (StandingOrder, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	// lock prevents concurrent transactions from reading a stale balance.
	GetAccountBalance(ctx context.Context, accountID uuid.UUID) (string, error)
	GetAccountByIBAN(ctx context.Context, iban string) (Account, error)
	GetAccountByIBANForUpdate(ctx context.Context, iban string) (Account, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetBeneficiaryByIBAN(ctx context.Context, arg GetBeneficiaryByIBANParams) (Beneficiary, error)
	GetPaymentOrder(ctx context.Context, id uuid.UUID) (PaymentOrder, error)
	GetPaymentOrderByIdempotency(ctx context.Context, arg GetPaymentOrderByIdempotencyParams) (PaymentOrder, error)
	GetPaymentOrderForUpdate(ctx context.Context, id uuid.UUID) (PaymentOrder, error)
	GetSettlementAccount(ctx context.Context) (Account, error)
	GetSettlementAccountForUpdate(ctx context.Context) (Account, error)
	GetStandingOrder(ctx context.Context, id uuid.UUID) (StandingOrder, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAccountTransactions(ctx context.Context, arg ListAccountTransactionsParams) ([]Entry, error)
	// locks row for update, prevents TOCTOU races
	ListAccountsByOwner(ctx context.Context, ownerID uuid.NullUUID) ([]Account, error)
	ListAccountsForUpdate(ctx context.Context, accountIds []uuid.UUID) ([]Account, error)
	ListAuditEventsAfter(ctx context.Context, arg ListAuditEventsAfterParams) ([]AuditEvent, error)
	ListBeneficiaries(ctx context.Context, ownerID uuid.UUID) ([]Beneficiary, error)
	ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]Entry, error)
	ListEntriesByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Entry, error)
	ListPaymentOrdersByOwner(ctx context.Context, arg ListPaymentOrdersByOwnerParams) ([]PaymentOrder, error)
	ListStandingOrdersByOwner(ctx context.Context, ownerID uuid.UUID) ([]StandingOrder, error)
	LookupPayeeByIBAN(ctx context.Context, iban string) (LookupPayeeByIBANRow, error)
	MarkPaymentBooked(ctx context.Context, arg MarkPaymentBookedParams) (PaymentOrder, error)
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (PaymentOrder, error)
	MarkPaymentProcessing(ctx context.Context, paymentOrderID uuid.UUID) (PaymentOrder, error)
	RecoverStalePayments(ctx context.Context, staleSeconds int32) (int64, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateStandingOrder(ctx context.Context, arg UpdateStandingOrderParams) (StandingOrder, error)
}

var _ Querier = (*Queries)(nil)
