// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standing_orders.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const advanceStandingOrder = `-- name: AdvanceStandingOrder :one
UPDATE standing_orders
SET occurrences_created = occurrences_created + 1,
    next_execution_at = $1,
    status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND status = 'ACTIVE'
RETURNING id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at
`

type AdvanceStandingOrderParams struct {
	NextExecutionAt time.Time `json:"next_execution_at"`
	Status          string    `json:"status"`
	StandingOrderID uuid.UUID `json:"standing_order_id"`
}

func (q *Queries) AdvanceStandingOrder(ctx context.Context, arg AdvanceStandingOrderParams) (StandingOrder, error) {
	row := q.db.QueryRowContext(ctx, advanceStandingOrder, arg.NextExecutionAt, arg.Status, arg.StandingOrderID)
	var i StandingOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.CreditorReference,
		&i.TransferType,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.MaxOccurrences,
		&i.OccurrencesCreated,
		&i.NextExecutionAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimDueStandingOrders = `-- name: ClaimDueStandingOrders :many
SELECT id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at FROM standing_orders
WHERE status = 'ACTIVE' AND next_execution_at <= CURRENT_TIMESTAMP
ORDER BY next_execution_at, id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) ClaimDueStandingOrders(ctx context.Context, batchSize int32) ([]StandingOrder, error) {
	rows, err := q.db.QueryContext(ctx, claimDueStandingOrders, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandingOrder
	for rows.Next() {
		var i StandingOrder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.SourceAccountID,
			&i.BeneficiaryAccountID,
			&i.BeneficiaryName,
			&i.BeneficiaryIban,
			&i.BeneficiaryBic,
			&i.Amount,
			&i.Currency,
			&i.Purpose,
			&i.CreditorReference,
			&i.TransferType,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.MaxOccurrences,
			&i.OccurrencesCreated,
			&i.NextExecutionAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createStandingOrder = `-- name: CreateStandingOrder :one
INSERT INTO standing_orders (
    owner_id, source_account_id, beneficiary_account_id, beneficiary_name,
    beneficiary_iban, beneficiary_bic, amount, currency, purpose,
    creditor_reference, transfer_type, frequency, start_date, end_date,
    max_occurrences, next_execution_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, 'EUR', $8,
    $9, $10, $11, $12, $13,
    $14, $15
)
RETURNING id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at
`

type CreateStandingOrderParams struct {
	OwnerID              uuid.UUID      `json:"owner_id"`
	SourceAccountID      uuid.UUID      `json:"source_account_id"`
	BeneficiaryAccountID uuid.NullUUID  `json:"beneficiary_account_id"`
	BeneficiaryName      string         `json:"beneficiary_name"`
	BeneficiaryIban      string         `json:"beneficiary_iban"`
	BeneficiaryBic       sql.NullString `json:"beneficiary_bic"`
	Amount               string         `json:"amount"`
	Purpose              sql.NullString `json:"purpose"`
	CreditorReference    sql.NullString `json:"creditor_reference"`
	TransferType         string         `json:"transfer_type"`
	Frequency            string         `json:"frequency"`
	StartDate            time.Time      `json:"start_date"`
	EndDate              sql.NullTime   `json:"end_date"`
	MaxOccurrences       sql.NullInt32  `json:"max_occurrences"`
	NextExecutionAt      time.Time      `json:"next_execution_at"`
}

func (q *Queries) CreateStandingOrder(ctx context.Context, arg CreateStandingOrderParams) (StandingOrder, error) {
	row := q.db.QueryRowContext(ctx, createStandingOrder,
		arg.OwnerID,
		arg.SourceAccountID,
		arg.BeneficiaryAccountID,
		arg.BeneficiaryName,
		arg.BeneficiaryIban,
		arg.BeneficiaryBic,
		arg.Amount,
		arg.Purpose,
		arg.CreditorReference,
		arg.TransferType,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.MaxOccurrences,
		arg.NextExecutionAt,
	)
	var i StandingOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.CreditorReference,
		&i.TransferType,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.MaxOccurrences,
		&i.OccurrencesCreated,
		&i.NextExecutionAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStandingOrder = `-- name: DeleteStandingOrder :one
UPDATE standing_orders
SET status = 'CANCELLED', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND owner_id = $2
  AND status IN ('ACTIVE', 'PAUSED')
RETURNING id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at
`

type DeleteStandingOrderParams struct {
	StandingOrderID uuid.UUID `json:"standing_order_id"`
	OwnerID         uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteStandingOrder(ctx context.Context, arg DeleteStandingOrderParams) (StandingOrder, error) {
	row := q.db.QueryRowContext(ctx, deleteStandingOrder, arg.StandingOrderID, arg.OwnerID)
	var i StandingOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.CreditorReference,
		&i.TransferType,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.MaxOccurrences,
		&i.OccurrencesCreated,
		&i.NextExecutionAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStandingOrder = `-- name: GetStandingOrder :one
SELECT id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at FROM standing_orders WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStandingOrder(ctx context.Context, id uuid.UUID) (StandingOrder, error) {
	row := q.db.QueryRowContext(ctx, getStandingOrder, id)
	var i StandingOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.CreditorReference,
		&i.TransferType,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.MaxOccurrences,
		&i.OccurrencesCreated,
		&i.NextExecutionAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStandingOrdersByOwner = `-- name: ListStandingOrdersByOwner :many
SELECT id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at FROM standing_orders WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStandingOrdersByOwner(ctx context.Context, ownerID uuid.UUID) ([]StandingOrder, error) {
	rows, err := q.db.QueryContext(ctx, listStandingOrdersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandingOrder
	for rows.Next() {
		var i StandingOrder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.SourceAccountID,
			&i.BeneficiaryAccountID,
			&i.BeneficiaryName,
			&i.BeneficiaryIban,
			&i.BeneficiaryBic,
			&i.Amount,
			&i.Currency,
			&i.Purpose,
			&i.CreditorReference,
			&i.TransferType,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.MaxOccurrences,
			&i.OccurrencesCreated,
			&i.NextExecutionAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandingOrder = `-- name: UpdateStandingOrder :one
UPDATE standing_orders
SET amount = $1, purpose = $2,
    end_date = $3, max_occurrences = $4,
    status = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $6 AND owner_id = $7
RETURNING id, owner_id, source_account_id, beneficiary_account_id, beneficiary_name, beneficiary_iban, beneficiary_bic, amount, currency, purpose, creditor_reference, transfer_type, frequency, start_date, end_date, max_occurrences, occurrences_created, next_execution_at, status, created_at, updated_at
`

type UpdateStandingOrderParams struct {
	Amount          string         `json:"amount"`
	Purpose         sql.NullString `json:"purpose"`
	EndDate         sql.NullTime   `json:"end_date"`
	MaxOccurrences  sql.NullInt32  `json:"max_occurrences"`
	Status          string         `json:"status"`
	StandingOrderID uuid.UUID      `json:"standing_order_id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
}

func (q *Queries) UpdateStandingOrder(ctx context.Context, arg UpdateStandingOrderParams) (StandingOrder, error) {
	row := q.db.QueryRowContext(ctx, updateStandingOrder,
		arg.Amount,
		arg.Purpose,
		arg.EndDate,
		arg.MaxOccurrences,
		arg.Status,
		arg.StandingOrderID,
		arg.OwnerID,
	)
	var i StandingOrder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceAccountID,
		&i.BeneficiaryAccountID,
		&i.BeneficiaryName,
		&i.BeneficiaryIban,
		&i.BeneficiaryBic,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.CreditorReference,
		&i.TransferType,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.MaxOccurrences,
		&i.OccurrencesCreated,
		&i.NextExecutionAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
